import unitsData from '@/data/units.json';
import type { DemoDataStore, LeaseAuditRecord, LeaseRecord, PropertyIssue, Unit, WorkOrderRecord } from '@/types/domain';
import { flattenUnits } from '@/services/unit-matching';

const demoLeaseRecord: LeaseRecord = {
  lease_id: 'LEASE-MC-B-1204',
  unit_id: 'MC-B-1204',
  landlord: { name: 'Marina Crest Holdings W.L.L.', present: true, signed: true },
  tenant: { name: 'Aisha Rahman', present: true, signed: true },
  commencement_date: '2025-01-01',
  expiry_date: '2027-12-31',
  term_months: 36,
  stated_term_months: 36,
  monthly_rent: 3500,
  annual_rent: 42000,
  deposit_amount: 3500,
  security_deposit: 3500,
  currency: 'QAR',
  payment_frequency: 'monthly',
  escalation_clause: {
    is_defined: true,
    mechanism: '5% annual fixed escalation',
    percentage: 5,
    evidence: [
      {
        field: 'escalation_clause',
        page: 3,
        text: 'Rent escalation clause states a fixed 5% annual increase. This is demo-only and must be reviewed manually.',
        source: 'mock lease text extraction',
        confidence: 0.88,
      },
    ],
  },
  renewal_terms: 'Automatic renewal for successive 12-month periods unless either party gives 90 days written notice.',
  termination_terms: 'Termination for convenience requires 30 days written notice.',
  missing_fields: [],
  contradictions: [],
  review_flags: ['Mock AI output for a demo workflow; verify all extracted facts before approval.'],
  evidence: [
    { field: 'unit_id', page: 1, text: 'Detected unit reference: MC-B-1204.', source: 'mock lease text extraction', confidence: 0.74 },
    { field: 'landlord', page: 1, text: 'Landlord identified as Marina Crest Holdings W.L.L.', source: 'mock lease text extraction', confidence: 0.82 },
    { field: 'tenant', page: 1, text: 'Tenant identified as Aisha Rahman.', source: 'mock lease text extraction', confidence: 0.82 },
    { field: 'monthly_rent', page: 2, text: 'Monthly rent stated as QAR 3,500.00.', source: 'mock lease text extraction', confidence: 0.9 },
    { field: 'security_deposit', page: 2, text: 'Security deposit stated as QAR 3,500.00 (equal to one month rent).', source: 'mock lease text extraction', confidence: 0.9 },
    { field: 'escalation_clause', page: 3, text: 'Rent escalation clause states a fixed 5% annual increase, applied every 12 months.', source: 'mock lease text extraction', confidence: 0.88 },
  ],
  confidence: 0.84,
  is_mock: true,
  source_note: 'Demo-only lease record. This record is illustrative and must be reviewed before it is treated as a verified business fact.',
  status: 'pending_review',
  review_status: 'PENDING_REVIEW',
  created_at: '2025-01-02T00:00:00.000Z',
};

const demoIssue: PropertyIssue = {
  issue_id: 'ISSUE-MC-B-1204-001',
  unit_id: 'MC-B-1204',
  title: 'Mock ceiling stain and minor wall crack',
  description: 'This is a demo-generated issue record for a sample unit. The detection is illustrative and should be reviewed by a human before creating a work order.',
  observed_condition: 'Visible stain on ceiling and minor crack near window trim.',
  detected_equipment: ['ceiling light', 'window frame'],
  uncertainty_notes: ['This issue was generated by mock vision output for demonstration only.'],
  image_references: ['demo-unit-1204-1.jpg'],
  work_order: {
    title: 'Patch ceiling stain and seal trim crack',
    repair_description: 'Inspect, patch, and repaint the affected ceiling and trim area.',
    status: 'Draft',
  },
  status: 'Draft',
  created_at: '2025-01-03T00:00:00.000Z',
};

const demoWorkOrder: WorkOrderRecord = {
  work_order_id: 'WO-MC-B-1204-001',
  issue_id: demoIssue.issue_id,
  unit_id: 'MC-B-1204',
  title: demoIssue.work_order.title,
  description: demoIssue.work_order.repair_description,
  status: 'Draft',
  created_at: demoIssue.created_at,
  is_mock: true,
};

let store: DemoDataStore = createInitialStore();

function createInitialStore(): DemoDataStore {
  return {
    units: flattenUnits(unitsData),
    leases: [structuredClone(demoLeaseRecord)],
    issues: [structuredClone(demoIssue)],
    workOrders: [structuredClone(demoWorkOrder)],
    leaseAudit: [],
  };
}

export function resetDemoDataStore(): void { store = createInitialStore(); }
export function getDemoDataStore(): DemoDataStore { return store; }

export function getUnits(): Unit[] {
  return store.units;
}

export function getUnitById(unitId: string): Unit | undefined {
  return getUnits().find((unit) => unit.unit_id === unitId);
}

export function getLeaseByUnitId(unitId: string): LeaseRecord | undefined {
  return store.leases.find((lease) => lease.unit_id === unitId);
}

export function updateLease(leaseId: string, values: Partial<LeaseRecord>, reviewer = 'Property owner'): LeaseRecord | undefined {
  const lease = store.leases.find((item) => item.lease_id === leaseId);
  if (!lease) return undefined;
  const changes: LeaseAuditRecord['changes'] = {};
  for (const [key, after] of Object.entries(values)) {
    if (key === 'unit_id' || key === 'lease_id' || key === 'status' || key === 'review_status' || key === 'created_at') continue;
    const before = (lease as unknown as Record<string, unknown>)[key];
    if (JSON.stringify(before) !== JSON.stringify(after)) changes[key] = { before, after };
  }
  Object.assign(lease, values, { unit_id: lease.unit_id });
  lease.review_status = 'PENDING_REVIEW';
  lease.status = 'pending_review';
  recordLeaseAction(leaseId, 'SAVE_CORRECTIONS', changes, reviewer);
  return lease;
}

export function recordLeaseAction(leaseId: string, action: LeaseAuditRecord['action'], changes: LeaseAuditRecord['changes'] = {}, reviewer = 'Property owner'): void {
  store.leaseAudit.push({ id: `AUDIT-${store.leaseAudit.length + 1}`, leaseId, action, changes, reviewer, reviewedAt: new Date().toISOString() });
}

export function acceptLease(leaseId: string, reviewer = 'Property owner'): { lease?: LeaseRecord; error?: string } {
  const lease = store.leases.find((item) => item.lease_id === leaseId);
  if (!lease) return { error: 'Lease not found.' };
  const unit = store.units.find((item) => item.unit_id === lease.unit_id);
  if (!unit) return { error: `Unit ${lease.unit_id} was not found.` };
  if (unit.status !== 'available') return { error: `Unit ${lease.unit_id} is already occupied.` };
  unit.status = 'occupied';
  lease.review_status = 'ACCEPTED';
  lease.status = 'approved';
  recordLeaseAction(leaseId, 'ACCEPT', {}, reviewer);
  return { lease };
}

export function rejectLease(leaseId: string, reviewer = 'Property owner'): LeaseRecord | undefined {
  const lease = store.leases.find((item) => item.lease_id === leaseId);
  if (!lease) return undefined;
  lease.review_status = 'REJECTED';
  lease.status = 'rejected';
  recordLeaseAction(leaseId, 'REJECT', {}, reviewer);
  return lease;
}

export function getIssuesByUnitId(unitId: string): PropertyIssue[] {
  return store.issues.filter((issue) => issue.unit_id === unitId);
}

export function getWorkOrdersByUnitId(unitId: string): WorkOrderRecord[] {
  return store.workOrders.filter((workOrder) => workOrder.unit_id === unitId);
}
